/**
 * The quest catalogue.
 *
 * ## How the main line is built
 *
 * Each main quest unlocks the next by naming it in `unlock`, so the chain is data rather than
 * code: the engine moves a quest from locked to active the moment the one before it is claimed,
 * and nothing else has to know the order. `next` names what a claim opens, which is what the
 * panel shows as "mở khóa".
 *
 * The line follows what the game actually gates on — plant, care, a first stage, level 3, a
 * first breed, the first boss, ten stages, level 5 — so the quest that says "đạt cấp 3" is the
 * quest that opens the thing level 3 opens. A guide that promises something the game does not do
 * is worse than no guide.
 *
 * ## Why some quests read `current` and some do not
 *
 * A quest whose measure is a fact about the save — your level, how many stages you have cleared,
 * how many species you hold — reads it directly, so it is correct the moment it opens and repairs
 * itself if an event was missed. A quest that means "do this *now*" — run a combo, replay a
 * cleared stage — has no `current` on purpose: it can only be earned by the event.
 */

import type { QuestDef } from "./types";

/** The main line, in order. `unlock` chains them; `next` says what a claim opens. */
const MAIN: QuestDef[] = [
  {
    id: "main_01_plant",
    type: "main",
    title: "Gieo mầm đầu tiên",
    description: "Mọi thứ bắt đầu từ một hạt giống. Gieo cây đầu tiên để mở vườn.",
    objective: "Gieo 1 hạt",
    target: 1,
    icon: "🌱",
    priority: 10,
    rewards: { exp: 60, coins: 50, unlocks: ["Vòng chăm cây"] },
    unlock: null,
    next: ["main_02_care"],
    track: { event: "plant", mode: "count" },
  },
  {
    id: "main_02_care",
    type: "main",
    title: "Chăm sóc đầu tiên",
    description: "Chăm cây để tăng chỉ số. Đây là cách cây mạnh lên ngoài việc đấu.",
    objective: "Chăm cây 1 lần",
    target: 1,
    icon: "💧",
    priority: 20,
    rewards: { exp: 60, items: 5, unlocks: ["Chỉ số cây"] },
    unlock: { kind: "quest", id: "main_01_plant" },
    next: ["main_03_stage"],
    track: { event: "care", mode: "count" },
  },
  {
    id: "main_03_stage",
    type: "main",
    title: "Ải đầu tiên",
    description: "Đưa cây trưởng thành ra trận. Thắng ải 1 để mở ải kế tiếp.",
    objective: "Vượt ải đầu tiên",
    target: 1,
    icon: "⚔️",
    priority: 30,
    rewards: { exp: 120, coins: 80, unlocks: ["Ải 2"] },
    unlock: { kind: "quest", id: "main_02_care" },
    next: ["main_04_level3"],
    track: { event: "stage_completed", mode: "count" },
    current: (ctx) => ctx.stagesCleared,
  },
  {
    id: "main_04_level3",
    type: "main",
    title: "Cấp 3",
    description: "Cấp nhà lai mở thêm ô đất và loài mới. Vượt ải để lên cấp.",
    objective: "Đạt cấp 3",
    target: 3,
    icon: "🎖️",
    priority: 40,
    rewards: { exp: 100, geneCrystal: 1, unlocks: ["Bàn lai tạo"] },
    unlock: { kind: "quest", id: "main_03_stage" },
    next: ["main_05_breed"],
    track: { event: "level_up", mode: "high" },
    current: (ctx) => ctx.level,
  },
  {
    id: "main_05_breed",
    type: "main",
    title: "Lai tạo cây con",
    description: "Lai hai cây trưởng thành để sinh ra giống mới — nguồn sức mạnh lâu dài.",
    objective: "Lai tạo 1 cây con",
    target: 1,
    icon: "🧬",
    priority: 50,
    rewards: { exp: 140, geneCrystal: 1, unlocks: ["Đặc tính di truyền"] },
    unlock: { kind: "quest", id: "main_04_level3" },
    next: ["main_06_boss"],
    track: { event: "breed", mode: "count" },
  },
  {
    id: "main_06_boss",
    type: "main",
    title: "Hạ boss đầu tiên",
    description: "Mỗi 10 ải có một boss. Phần thưởng tinh thể lớn nhất nằm ở đó.",
    objective: "Đánh bại 1 boss",
    target: 1,
    icon: "👑",
    priority: 60,
    rewards: { exp: 250, geneCrystal: 2, items: 15, unlocks: ["Bậc Thung Lũng"] },
    unlock: { kind: "quest", id: "main_05_breed" },
    next: ["main_07_ten"],
    track: { event: "stage_completed", mode: "count", match: { boss: true } },
  },
  {
    id: "main_07_ten",
    type: "main",
    title: "Mười ải",
    description: "Đi sâu vào thang ải để mở bậc tiếp theo và nhận thưởng lớn hơn.",
    objective: "Vượt 10 ải",
    target: 10,
    icon: "🏔️",
    priority: 70,
    rewards: { exp: 400, coins: 500, unlocks: ["Bậc Vực Thẳm"] },
    unlock: { kind: "quest", id: "main_06_boss" },
    next: ["main_08_level5"],
    track: { event: "stage_completed", mode: "count" },
    current: (ctx) => ctx.stagesCleared,
  },
  {
    id: "main_08_level5",
    type: "main",
    title: "Cấp 5",
    description: "Cấp 5 mở ô đất mới và kho hạt rộng hơn. Chơi đều sẽ tới.",
    objective: "Đạt cấp 5",
    target: 5,
    icon: "🌟",
    priority: 80,
    rewards: { exp: 300, geneCrystal: 2, unlocks: ["Kỹ năng nâng cao"] },
    unlock: { kind: "quest", id: "main_07_ten" },
    track: { event: "level_up", mode: "high" },
    current: (ctx) => ctx.level,
  },
];

/** Optional work, open from early on. Never required to progress. */
const SIDE: QuestDef[] = [
  {
    id: "side_combo_10",
    type: "side",
    title: "Thử thách liên hoàn",
    description: "Đánh liên tiếp không bị trúng đòn. Chuỗi càng dài, thưởng càng đáng.",
    objective: "Đạt chuỗi 10 đòn",
    target: 10,
    icon: "🔥",
    priority: 210,
    rewards: { exp: 120, coins: 100 },
    unlock: { kind: "level", level: 3 },
    track: { event: "combo_reached", mode: "high" },
  },
  {
    id: "side_win_3",
    type: "side",
    title: "Ba trận thắng",
    description: "Thắng ở bất kỳ đâu — ải hay đấu tập — đều tính.",
    objective: "Thắng 3 trận",
    target: 3,
    icon: "🏆",
    priority: 220,
    rewards: { exp: 150, items: 10 },
    unlock: { kind: "level", level: 2 },
    track: { event: "enemy_defeated", mode: "count" },
    current: (ctx) => ctx.wins,
  },
  {
    id: "side_items_20",
    type: "side",
    title: "Tích trữ vật tư",
    description: "Vật tư dùng để chăm cây và mở ô đất. Càng nhiều càng linh hoạt.",
    objective: "Thu 20 vật tư",
    target: 20,
    icon: "🎒",
    priority: 230,
    rewards: { exp: 100, coins: 200 },
    unlock: { kind: "level", level: 2 },
    track: { event: "item_collected", mode: "count" },
  },
  {
    id: "side_replay_win",
    type: "side",
    title: "Chinh phục ải mới",
    description: "Thang chỉ đi lên — mỗi ải vượt qua là một lần, và lần nào cũng tính.",
    objective: "Vượt 3 ải mới",
    target: 3,
    icon: "🏔️",
    priority: 240,
    rewards: { exp: 110, items: 6 },
    unlock: { kind: "stage", stage: 3 },
    track: { event: "stage_completed", mode: "count" },
  },
  {
    id: "side_species_5",
    type: "side",
    title: "Năm giống cây",
    description: "Sưu tầm hạt của nhiều loài — mỗi loài có hệ và đặc tính khác nhau.",
    objective: "Sở hữu hạt của 5 loài",
    target: 5,
    icon: "📗",
    priority: 250,
    rewards: { exp: 130, geneCrystal: 1 },
    unlock: { kind: "level", level: 4 },
    track: { event: "item_collected", mode: "count" },
    current: (ctx) => ctx.speciesCount,
  },
];

/**
 * The daily shelf.
 *
 * Deliberately about the four things a session is made of — a fight, a stage, experience, items —
 * so a player who plays one way today is not handed three quests for a mode they are not in.
 * Rolled three at a time by the engine, and repeatable so tomorrow's roll can reuse them.
 */
const DAILY: QuestDef[] = [
  {
    id: "daily_win_3",
    type: "daily",
    title: "Thắng 3 trận",
    description: "Thắng ở bất kỳ chế độ nào trong hôm nay.",
    objective: "Thắng 3 trận",
    target: 3,
    icon: "⚔️",
    priority: 310,
    repeatable: true,
    rewards: { exp: 80, coins: 120 },
    unlock: { kind: "stage", stage: 2 },
    track: { event: "enemy_defeated", mode: "count" },
  },
  {
    id: "daily_stage_3",
    type: "daily",
    title: "Vượt 3 ải",
    description: "Ải nào cũng tính, kể cả ải đã vượt trước đây.",
    objective: "Vượt 3 ải",
    target: 3,
    icon: "🏔️",
    priority: 320,
    repeatable: true,
    rewards: { exp: 120, coins: 150 },
    unlock: { kind: "stage", stage: 2 },
    track: { event: "stage_completed", mode: "count" },
  },
  {
    id: "daily_exp_500",
    type: "daily",
    title: "Nhận 500 EXP",
    description: "EXP đến từ ải, chăm cây và lai tạo. Chơi là có.",
    objective: "Nhận 500 EXP hôm nay",
    target: 500,
    icon: "✨",
    priority: 330,
    repeatable: true,
    rewards: { exp: 60, items: 10 },
    unlock: { kind: "stage", stage: 2 },
    track: { event: "exp_gained", mode: "count" },
  },
  {
    id: "daily_items_20",
    type: "daily",
    title: "Thu 20 vật tư",
    description: "Vật tư rơi từ trận thắng và từ nhiệm vụ khác.",
    objective: "Thu 20 vật tư",
    target: 20,
    icon: "🎒",
    priority: 340,
    repeatable: true,
    rewards: { exp: 70, coins: 200 },
    unlock: { kind: "stage", stage: 2 },
    track: { event: "item_collected", mode: "count" },
  },
  {
    id: "daily_care_5",
    type: "daily",
    title: "Chăm cây 5 lần",
    description: "Chăm cây tăng chỉ số và giữ cây khoẻ trước các ải sâu.",
    objective: "Chăm cây 5 lần",
    target: 5,
    icon: "💧",
    priority: 350,
    repeatable: true,
    rewards: { exp: 90, items: 8 },
    unlock: { kind: "stage", stage: 2 },
    track: { event: "care", mode: "count" },
  },
  {
    id: "daily_combo_8",
    type: "daily",
    title: "Chuỗi 8 đòn",
    description: "Một chuỗi dài trong bất kỳ trận nào hôm nay.",
    objective: "Đạt chuỗi 8 đòn",
    target: 8,
    icon: "🔥",
    priority: 360,
    repeatable: true,
    rewards: { exp: 100, coins: 100 },
    unlock: { kind: "stage", stage: 2 },
    track: { event: "combo_reached", mode: "high" },
  },
];

/** One-time marks. The panel's achievement shelf is the record of a garden's history. */
const ACHIEVEMENTS: QuestDef[] = [
  {
    id: "ach_first_levelup",
    type: "achievement",
    title: "Lần đầu lên cấp",
    description: "Cây đầu tiên của bạn lên một cấp.",
    objective: "Lên cấp lần đầu",
    target: 2,
    icon: "🎖️",
    priority: 410,
    rewards: { exp: 40, items: 10 },
    unlock: null,
    track: { event: "level_up", mode: "high" },
    current: (ctx) => ctx.level,
  },
  {
    id: "ach_level_5",
    type: "achievement",
    title: "Nhà lai tạo cấp 5",
    description: "Cấp 5 mở ô đất và kho hạt rộng hơn.",
    objective: "Đạt cấp 5",
    target: 5,
    icon: "🌟",
    priority: 420,
    rewards: { coins: 300, geneCrystal: 1 },
    unlock: null,
    track: { event: "level_up", mode: "high" },
    current: (ctx) => ctx.level,
  },
  {
    id: "ach_stages_10",
    type: "achievement",
    title: "Mười ải đã qua",
    description: "Đi hết mười ải đầu của thang ải.",
    objective: "Vượt 10 ải",
    target: 10,
    icon: "🏔️",
    priority: 430,
    rewards: { coins: 500, geneCrystal: 2 },
    unlock: null,
    track: { event: "stage_completed", mode: "count" },
    current: (ctx) => ctx.stagesCleared,
  },
  {
    id: "ach_breed_5",
    type: "achievement",
    title: "Năm đời cây",
    description: "Lai tạo năm cây con. Mỗi đời là một bước tiến về chỉ số.",
    objective: "Lai tạo 5 cây",
    target: 5,
    icon: "🧬",
    priority: 440,
    rewards: { coins: 400, items: 20 },
    unlock: null,
    track: { event: "breed", mode: "count" },
  },
  {
    id: "ach_combo_15",
    type: "achievement",
    title: "Chuỗi mười lăm",
    description: "Một chuỗi mười lăm đòn không bị ngắt.",
    objective: "Đạt chuỗi 15 đòn",
    target: 15,
    icon: "🔥",
    priority: 450,
    rewards: { geneCrystal: 2, coins: 300 },
    unlock: null,
    track: { event: "combo_reached", mode: "high" },
  },
  {
    id: "ach_score_10000",
    type: "achievement",
    title: "Mười nghìn điểm",
    description: "Tổng EXP kiếm được từ khi bắt đầu chơi.",
    objective: "Đạt tổng 10.000 EXP",
    target: 10000,
    icon: "💎",
    priority: 460,
    rewards: { geneCrystal: 3, coins: 800 },
    unlock: null,
    track: { event: "exp_gained", mode: "count" },
    current: (ctx) => ctx.score,
  },
];

/** Every quest, in one list. The engine and the UI both read this and nothing else. */
export const QUEST_CATALOG: readonly QuestDef[] = Object.freeze([...MAIN, ...SIDE, ...DAILY, ...ACHIEVEMENTS]);

/** The tab labels, in the order the panel shows them. */
export const QUEST_TABS: { type: QuestDef["type"]; label: string; icon: string }[] = [
  { type: "main", label: "Chính", icon: "🎯" },
  { type: "side", label: "Phụ", icon: "🧭" },
  { type: "daily", label: "Hằng ngày", icon: "📅" },
  { type: "achievement", label: "Thành tựu", icon: "🏅" },
];
