import { SPECIES } from "../src/config/species";
const grows = SPECIES.map((s) => s.growMinutes);
const prices = SPECIES.map((s) => s.seedPrice);
const uniq = (a) => new Set(a).size;
const q = (a, p) => a.slice().sort((x, y) => x - y)[Math.floor(a.length * p)];
console.log("growMinutes: " + uniq(grows) + " distinct, range " + Math.min.apply(null, grows) + "-" + Math.max.apply(null, grows));
console.log("seedPrice:   " + uniq(prices) + " distinct, range " + Math.min.apply(null, prices) + "-" + Math.max.apply(null, prices));
console.log("grow  p10/p50/p90: " + q(grows, 0.1) + " / " + q(grows, 0.5) + " / " + q(grows, 0.9));
console.log("price p10/p50/p90: " + q(prices, 0.1) + " / " + q(prices, 0.5) + " / " + q(prices, 0.9));
const slow = SPECIES.filter((s) => s.growMinutes >= 45).slice(0, 3);
const fast = SPECIES.filter((s) => s.growMinutes <= 16).slice(0, 3);
for (const s of fast) console.log("  fast: " + s.name.padEnd(20) + s.growMinutes + "m  " + s.seedPrice + " xu  " + s.archetype);
for (const s of slow) console.log("  slow: " + s.name.padEnd(20) + s.growMinutes + "m  " + s.seedPrice + " xu  " + s.archetype);